day18/CstDay18/CstDemo1/Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CstDemo1.Models
{
    public class UserInfo
    {
        public int UserID { get; set; }

        [StringLength(20,ErrorMessage ="Length < 20")]
        [Required(ErrorMessage="* required.")]

        public string UserName { get; set; }
        [Range(8,10)]
        [Required(ErrorMessage= "* required.")]
        public string UserEmail { get; set; }


        public string UserMobile { get; set; }

    }
}

day18/CstDay18/CstDemo1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CstDemo1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

day18/CstDay18/CstDemo1/Controllers/UserListController.cs
using CstDemo1.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CstDemo1.Controllers
{
    public class UserListController : Controller
    {
        // GET: UserList
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            //var userInfo = new UserInfo();
            //userInfo.UserID = 10;
            //userInfo.UserName = "Tom";
            //userInfo.UserEmail = "tom@cstcollege.ca";
            //userInfo.UserMobile = "647-833-8777";

            string testStr = "Welcome to CST College!!!";

            ViewData["testStr"] = testStr;

            ViewBag.myName = "Cst College Student Xun Dai.";
            TempData["cstName"] = "Hello CST College!!!";

            return View();
        }

        public ActionResult Show()
        {
            string connStr = SqlHelper.GetConnectionString();
            string sqlTxt = "Select * from userinfo where delflag=0";
            using (SqlDataAdapter adapter=new SqlDataAdapter(sqlTxt,connStr))
            {
                DataTable dt = new DataTable();
                adapter.Fill(dt);
                ViewData["dt"] = dt;

            }
                return View();
        }

        //respond by get.
        public ActionResult AddUser()
        {
            return View();
        }

        public ActionResult ProcessAddUser(FormCollection collection)
        {
            // return Content("add action respond!!!");

            string userName = Request["UserName"];
            int userAge = int.Parse(Request["UserAge"]??"10");
            string userEmail = Request["UserEmail"];
            string userMobile = Request["UserMobile"];
            // save record to database. NoQuery

            string insertSql = "insert UserInfo (UserName,UserPassword,UserAge,UserEmail,UserMobile) values (@UserName,'Cst100.com',@UserAge,'1123@gmail.com',@UserMobile)";

            SqlHelper.ExecuteNoQuery(insertSql, new SqlParameter("@UserName", userName), new SqlParameter("@UserAge", userAge), new SqlParameter("@UserMobile", userMobile), new SqlParameter("@UserEmail", userEmail));

            //, new SqlParameter("@UserEmail", userEmail), new SqlParameter("@UserMobile", userMobile)

            return RedirectToAction("Show");
        }

        public ActionResult Delete(int ID)
        {
            //return Content("delete user");
            string deleteSql = "delete from userinfo where userID=@userid";

            SqlHelper.ExecuteNoQuery(deleteSql, new SqlParameter("@userid", ID));

            return RedirectToAction("Show");
        }

        public ActionResult AddwithValid()
        {
            //return RedirectToAction("Show");
            return View();
        }
    }
}

day18/CstDay18/CstDemo1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/shared/_Layout_CST.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

day18/CstDay18/CstDemo1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/shared/_Layout_CST.cshtml";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

day18/CstDay18/CstDemo1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/shared/_Layout_CST.cshtml";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

day18/CstDay18/CstDemo1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Xun Dai's ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

day18/CstDay18/CstDemo1/Views/Shared/_Layout_CST.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  Xun Dai's ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("ShowAllUser", "Show", "UserList")</li>
                    <li>@Html.ActionLink("ShowDemo", "List", "UserList")</li>
                    <li>@Html.ActionLink("AddUser", "AddUser", "UserList")</li>
                    <li>@Html.ActionLink("AddUserwithValid", "AddwithValid", "UserList")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Xun Dai's ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

day18/CstDay18/CstDemo1/Views/UserList/AddUser.cshtml
@{
    ViewBag.Title = "AddUser";
    Layout = "~/Views/Shared/_Layout_CST.cshtml";
}

<h2>AddUser</h2>
<div class="container">
    <form method="post" action="/UserList/ProcessAddUser">
        <table>
            <tr>
                <td>UserName</td>
                <td><input type=@Html.TextBox("UserName")</td>
            </tr>
            <tr>
                <td>UserAge</td>
                <td><input type=@Html.TextBox("UserAge")</td>
            </tr>
            <tr>
                <td>UserEmail</td>
                <td><input type=@Html.TextBox("UserEmail")</td>
            </tr>
            <tr>
                <td>UserMobile</td>
                <td><input type=@Html.TextBox("UserMobile")</td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="add user"></td>
            </tr>
        </table>
    </form>
</div>

day18/CstDay18/CstDemo1/Views/UserList/AddwithValid.cshtml
@model CstDemo1.Models.UserInfo

@{
    ViewBag.Title = "AddwithValid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddwithValid</h2>

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserMobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserMobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserMobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

day18/CstDay18/CstDemo1/Views/UserList/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/shared/_Layout_CST.cshtml";
}

<h2>List All Users</h2>

@{ 
    string cstStr = ViewData["testStr"].ToString();
    
    <h2>@cstStr</h2>
    <h2>@ViewBag.myName</h2>
    <h3>@TempData["cstName"]</h3>

}

day18/CstDay18/CstDemo1/Views/UserList/Show.cshtml
@using System.Data;

@{
    ViewBag.Title = "Show";
    Layout = "~/Views/shared/_Layout_CST.cshtml";
}

<h2>List All Users</h2>

@{
    DataTable dt = (DataTable)ViewData["dt"];
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script type="text/javascript">
    $('.Delete').on('click', function () {
        return confirm('Are you SURE?');
    });
</script>

<table style="width:100%">
    <tr>
        <th style="text-align:center">UserID</th>
        <th style="text-align:center">UserName</th>
        <th style="text-align:center">UserAge</th>
        <th style="text-align:center">UserEmail</th>
        <th style="text-align:center">UserMobile</th>
        <th style="text-align:center">Delete</th>
    </tr>

    @foreach (DataRow row in dt.Rows)
    {
        <tr>
            <td style="text-align:center">@row["UserID"]</td>
            <td style="text-align:center">@row["UserName"]</td>
            <td style="text-align:center">@row["UserAge"]</td>
            <td style="text-align:center">@row["UserEmail"]</td>
            <td style="text-align:center">@row["UserMobile"]</td>
            <td style="text-align:center">@Html.ActionLink("DeleteUser", "Delete", new{ ID= row["UserID"]},new{})</td>
        </tr>
    }

</table>